### ISSUE TITLE
keepAlive() on only one side causes error

### ISSUE THREAD

**Issue by gmaclennan** [holepunchto/hyperswarm-secret-stream#18]
This may be just a docs issue: If you set keepAlive() on one side of the stream, but not the other, then things will break because the empty buffers get passed through to the stream consumer. When using this with Hypercore this causes an error in protomux because it tries to process the empty buffer from secret-stream.

Maybe the docs for this method should state "Keep alive must be set on both sides of the stream, because otherwise things will break"?

**Comment by mafintosh** [comment]
Feel free to document that
